### ISSUE TITLE
Fix generate_text_files.py

### ISSUE THREAD

**Issue by pranayagra** [DhruvaBansal00/SBHMM-HTK#2]
Currently, the entire dataset for all users determines the text_files that are generated in order to run HMMs. However, if we are only testing/training on a subset of our dataset, then the files do not represent the data.

Potential solution: generate the text_files during testing/training, not during prepare_data

**Comment by DhruvaBansal00** [comment]
I think we took care of this as well. @pranayagra do you remember what this is about?
